[icedos.desktop]
accentColor = "B067FD" # With gnome enabled this is getting overriden by gnome's selected accent color hex code
autologinUser = ""
timezone = "Europe/Bucharest"
wallpaper = "" # Absolute path to image. Empty = user/UI-managed (no rebuild override).

[icedos.desktop.bookmarks]
extras = []
documents = true
downloads = true
music = true
pictures = true
public = true
templates = true
videos = true

[icedos.desktop.windows]
activeHint = true
activeHintSize = 1
maximizeButton = true
minimizeButton = true

[icedos.desktop.users.username.idle.disableMonitors]
enable = true
seconds = 600

[icedos.desktop.users.username.idle.lock]
enable = true
seconds = 900

[icedos.desktop.users.username.idle.suspend]
enable = true
seconds = 1800
